### ISSUE TITLE
constant crashes 

### ISSUE THREAD

**Issue by dvvvsh** [WietseWind/xrp-ledgerstats#5]
I've tried to run it 100000 times yesterday, colab, lighting.ai etc. all over and it doesn't get past 100 calls. 
![Screenshot 2024-12-01 205234](https://github.com/user-attachments/assets/2c0f78b7-4748-48f8-af60-b773722382d3)
is this issue on my end orrr

**Comment by WietseWind** [comment]
The ledger is now too big to fit in a node process memory. This project is EOL :(
